services:
  - type: web
    name: stampnsign
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend/app && uvicorn main:app --host=0.0.0.0 --port=$PORT